apiVersion: ENC[AES256_GCM,data:EcA=,iv:JI6PeKOzuc2XLjQ1N2gmB67Jj9xPG/+BCWW1RonA5cE=,tag:G7qPVFXpuVvUNWT4vb1CJw==,type:str]
data:
    mysecret: ENC[AES256_GCM,data:V5ZgQ8b6f47NYSkCYRSgrA==,iv:uZilvKPOP7Idg4vWM2vHieeh4dys2eQ5DUqC9fjH+70=,tag:NGMU3JKpRGyeXNS4hEyhKw==,type:str]
kind: ENC[AES256_GCM,data:GswgIZSv,iv:WEx7pDEGL4aFdz+/5rXZVXOT1+b+UerEoswsI2JwZDA=,tag:WUrgRvAbrqQUOFraapQwQw==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:fbAPPw==,iv:iMj9deiMs1bUJHqIHycudoWxpIa3UK/syZWDy+HXjP8=,tag:8G8avs3+RhxW7cECVXXY3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-07T08:20:23Z"
    mac: ENC[AES256_GCM,data:qfWqynoP6+yNwQHJzeNK2twlnXNjS6kf7eg9xNdHYqWnrxG/XAiZg83VjvsCAYhm++B6QEmLSZwlfivMUGPLUVLTXnpPKzyNZwjjph78tuOwTuRCukjSx4PY8Rzmuh2N/7KodUH08VKbEpZvOKgKwc+daW+o/X52Eh9dzCfpyao=,iv:IEQA4sVkZqoLdQGraeE7pt/o3yFELqaFusQU4h/RIB8=,tag:PJojybvUMb1DnD2DzAhW4A==,type:str]
    pgp:
        - created_at: "2022-05-07T08:20:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAwhDjPYyJvuGAQgAULNHrMLg5yRoS4SKJJanBuSpkYvR6bc+Xdqjbkb4Yydn
            bIHqBOwsaGnCG0E4yw5EQIje8hjgfcnw64P+15mCaelFI4mpLbphEYBIQgcvPQYU
            8e67lklopEgZZ+7f312J0QC5xWZ8ZO0spfQjCqqoyedkPiQ+bg7fTcUeauPtZDH5
            lBcPkHmPAwHcuHZ1qx+iRaEFrOkRccOocGo3GfswiDiDb7qP/ZVW+sHVZQg75Tn/
            h/tdEbGttyQVhP5P6+AAKFuvDbMF4JPxeqr5CQj/xp4Su4q7X031KeOc/0gp5Q24
            hxVjv6CzxazgjIBIngNAapednkAvkW6emEldYzp6E9LmAagH39dq2huGcKLYzCdk
            MRxHJGwc6SmnFFZaGImkm2CGoLg9j60KmFmPBtBl+BtLD2t2FthzxtJVWuK/Rxav
            nOSQrCkzGGVYGZwsJllEJBjM4l912E0A
            =xbMF
            -----END PGP MESSAGE-----
          fp: 50FF6C7D8910F5F90F41AA6DC598763A161C187A
    unencrypted_suffix: _unencrypted
    version: 3.7.2
